"""Pure builders for the PR comment, Job Summary, and action outputs.

Everything here is deterministic and free of I/O so it can be unit-tested. The
caller is responsible for masking secrets (see :mod:`aiqa_action.masking`) and
for the actual writes (see :mod:`aiqa_action.github`).
"""

from __future__ import annotations

from typing import Any

from aiqa.reporting.portal.models import ExecutionRun

from .grouping import FailureGroup

COMMENT_MARKER = "<!-- aiqa-failure-analysis -->"

_READINESS_EMOJI = {"READY": "✅", "AT_RISK": "⚠️", "NOT_READY": "❌"}


def _readiness(run: ExecutionRun | None) -> str:
    # Normalise the engine's "NOT READY" / "AT RISK" to the canonical form.
    raw = (run.release_readiness if run else "") or "UNKNOWN"
    return raw.strip().upper().replace(" ", "_")


def _known_new(run: ExecutionRun | None, memories: dict[str, Any]) -> tuple[int, int]:
    """Split failures into (new, known) using the knowledge base + regressions."""
    if run is None:
        return 0, 0
    known = 0
    for f in run.failures:
        mem = memories.get(f.signature)
        if mem is not None and getattr(mem, "seen_before", False):
            known += 1
    new = max(0, len(run.failures) - known)
    return new, known


def _top_group(groups: list[FailureGroup]) -> FailureGroup | None:
    return groups[0] if groups else None


# --------------------------------------------------------------------------- #
# PR comment
# --------------------------------------------------------------------------- #
def build_pr_comment(
    run: ExecutionRun | None,
    *,
    groups: list[FailureGroup] | None = None,
    memories: dict[str, Any] | None = None,
    report_url: str = "",
    artifact_url: str = "",
) -> str:
    groups = groups or []
    memories = memories or {}
    if run is None:
        return (
            f"{COMMENT_MARKER}\n## 🤖 AIQA Failure Analysis\n\n"
            "Analysis could not be completed. See the job log for details."
        )
    if not run.failures:
        return build_success_comment(run)

    new, known = _known_new(run, memories)
    top = _top_group(groups)
    readiness = _readiness(run)
    emoji = _READINESS_EMOJI.get(readiness, "")

    lines = [
        COMMENT_MARKER,
        "## 🤖 AIQA Failure Analysis",
        "",
        f"**Status:** {emoji} {readiness.replace('_', ' ')} · "
        f"**Quality score:** {run.quality_score}/100",
        "",
        "### Tests",
        f"- {run.total} total",
        f"- {run.passed} passed",
        f"- {run.failed} failed",
    ]
    if run.skipped:
        lines.append(f"- {run.skipped} skipped")

    if run.categories:
        lines += ["", "### AI Classification"]
        for cat, n in sorted(run.categories.items(), key=lambda kv: kv[1], reverse=True):
            lines.append(f"- {cat}: {n}")

    if top:
        lines += [
            "",
            "### Top Root Cause",
            f"{top.root_cause}",
            "",
            f"**Confidence:** {top.confidence}%",
            f"**Owner:** {top.owner or 'Unassigned'}",
        ]
        if top.suggested_fix:
            lines += ["", "**Suggested Fix:**", top.suggested_fix]

    lines += ["", f"**New failures:** {new}  ·  **Known / recurring:** {known}"]

    links = []
    if report_url:
        links.append(f"[View AIQA Report]({report_url})")
    if artifact_url:
        links.append(f"[Download AIQA Report]({artifact_url})")
    if links:
        lines += ["", " · ".join(links)]

    lines += ["", "<sub>Generated by AIQA · offline by default.</sub>"]
    return "\n".join(lines)


def build_success_comment(run: ExecutionRun | None) -> str:
    total = run.total if run else 0
    passed = run.passed if run else 0
    return (
        f"{COMMENT_MARKER}\n## ✅ AIQA Failure Analysis\n\n"
        f"No failures detected — {passed}/{total} tests passed. "
        "Nothing to triage. 🎉"
    )


# --------------------------------------------------------------------------- #
# Job Summary ($GITHUB_STEP_SUMMARY)
# --------------------------------------------------------------------------- #
def build_step_summary(
    run: ExecutionRun | None,
    *,
    groups: list[FailureGroup] | None = None,
    memories: dict[str, Any] | None = None,
    report_path: str = "",
    warnings: list[str] | None = None,
) -> str:
    groups = groups or []
    warnings = warnings or []
    lines = ["# 🤖 AIQA Analysis", ""]

    if run is None:
        lines += ["Analysis did not produce a result.", ""]
        if warnings:
            lines += ["**Warnings:**", *[f"- {w}" for w in warnings]]
        return "\n".join(lines)

    if not run.failures:
        lines += [
            f"✅ **No failures** — {run.passed}/{run.total} tests passed.",
            "",
            f"**Release readiness:** {_readiness(run)}  ·  "
            f"**Quality score:** {run.quality_score}/100",
        ]
        return "\n".join(lines)

    readiness = _readiness(run)
    emoji = _READINESS_EMOJI.get(readiness, "")
    lines += [
        "## Test Statistics",
        "",
        "| Total | Passed | Failed | Skipped | Pass rate |",
        "|------:|-------:|-------:|--------:|----------:|",
        f"| {run.total} | {run.passed} | {run.failed} | {run.skipped} | {run.pass_rate}% |",
        "",
        f"**Release readiness:** {emoji} {readiness}  ·  "
        f"**Quality score:** {run.quality_score}/100",
    ]

    if run.categories:
        lines += ["", "## Failure Classification", "", "| Category | Count |", "|---|---:|"]
        for cat, n in sorted(run.categories.items(), key=lambda kv: kv[1], reverse=True):
            lines.append(f"| {cat} | {n} |")

    top = _top_group(groups)
    if top:
        lines += [
            "",
            "## Root Cause",
            f"- **Cause:** {top.root_cause}",
            f"- **Confidence:** {top.confidence}%",
            f"- **Owner:** {top.owner or 'Unassigned'}",
        ]
        if top.suggested_fix:
            lines.append(f"- **Suggested fix:** {top.suggested_fix}")

    grouped = [g for g in groups if g.count > 1]
    if grouped:
        lines += ["", "## Grouped Failures"]
        for g in grouped:
            lines.append(
                f"- **{g.category}** — {g.count} tests, {g.confidence}% confidence: {g.root_cause}"
            )

    if report_path:
        lines += ["", f"📄 Full report: `{report_path}`"]
    if warnings:
        lines += ["", "## Warnings", *[f"- {w}" for w in warnings]]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Action outputs
# --------------------------------------------------------------------------- #
def build_outputs(
    run: ExecutionRun | None,
    *,
    report_path: str = "",
    report_url: str = "",
    artifact_name: str = "",
) -> dict[str, str]:
    if run is None:
        return {
            "report-path": report_path,
            "report-url": report_url,
            "artifact-name": artifact_name,
            "failure-count": "0",
            "failure-category": "",
            "overall-status": "ANALYSIS_FAILED",
            "quality-score": "0",
        }
    top_category = ""
    if run.categories:
        top_category = max(run.categories.items(), key=lambda kv: kv[1])[0]
    return {
        "report-path": report_path,
        "report-url": report_url,
        "artifact-name": artifact_name,
        "failure-count": str(run.failed),
        "failure-category": top_category,
        "overall-status": _readiness(run),
        "quality-score": str(run.quality_score),
    }
