"""Generate concrete locator strings for multiple frameworks.

Given a resolved :class:`~aiqa.healing.dom.Element` and a chosen *strategy*,
produce the equivalent locator in Playwright, Selenium, CSS, XPath and Robot
Framework syntaxes. Everything here is pure string construction — no framework
imports — so it works anywhere.
"""

from __future__ import annotations

from .dom import Element
from .models import LocatorSuggestion


def _css_escape(value: str) -> str:
    return value.replace("'", "\\'")


def _by_test_id(el: Element) -> LocatorSuggestion | None:
    found = el.test_id()
    if not found:
        return None
    attr, value = found
    css = f"[{attr}='{_css_escape(value)}']"
    return LocatorSuggestion(
        strategy="test-id",
        confidence=95,
        reason=f"Stable test hook '{attr}' is present and is the most change-resistant locator.",
        playwright=(
            f"page.get_by_test_id('{value}')" if attr == "data-testid" else f'page.locator("{css}")'
        ),
        selenium=f'driver.find_element(By.CSS_SELECTOR, "{css}")',
        css=css,
        xpath=f"//*[@{attr}='{value}']",
        robotframework=f"css={css}",
    )


def _by_id(el: Element) -> LocatorSuggestion | None:
    el_id = el.attr("id")
    if not el_id:
        return None
    # IDs that look autogenerated are less reliable.
    autogen = any(ch.isdigit() for ch in el_id) and len(el_id) > 12
    return LocatorSuggestion(
        strategy="id",
        confidence=70 if autogen else 90,
        reason=(
            "Element id is present"
            + (
                " but looks autogenerated, so it may not be stable."
                if autogen
                else " and uniquely identifies the element."
            )
        ),
        playwright=f"page.locator('#{el_id}')",
        selenium=f"driver.find_element(By.ID, '{el_id}')",
        css=f"#{el_id}",
        xpath=f"//*[@id='{el_id}']",
        robotframework=f"id={el_id}",
    )


_ROLE_BY_TAG = {
    "a": "link",
    "button": "button",
    "input": "textbox",
    "select": "combobox",
    "textarea": "textbox",
}


def _by_role(el: Element) -> LocatorSuggestion | None:
    role = el.attr("role") or _ROLE_BY_TAG.get(el.tag)
    name = el.attr("aria-label") or el.text
    if not role or not name:
        return None
    name = name.strip()[:60]
    return LocatorSuggestion(
        strategy="role",
        confidence=85,
        reason="Accessible role and name are semantic and resilient to markup refactors.",
        playwright=f"page.get_by_role('{role}', name='{_css_escape(name)}')",
        selenium=f"driver.find_element(By.XPATH, \"//*[@role='{role}' or self::{el.tag}][normalize-space()='{name}']\")",
        css="",
        xpath=f"//{el.tag}[normalize-space()='{name}']",
        robotframework=f"xpath=//{el.tag}[normalize-space()='{name}']",
    )


def _by_name(el: Element) -> LocatorSuggestion | None:
    name = el.attr("name")
    if not name:
        return None
    css = f"[name='{_css_escape(name)}']"
    return LocatorSuggestion(
        strategy="name",
        confidence=80,
        reason="The form control 'name' attribute is stable across visual redesigns.",
        playwright=f'page.locator("{css}")',
        selenium=f"driver.find_element(By.NAME, '{name}')",
        css=css,
        xpath=f"//{el.tag}[@name='{name}']",
        robotframework=f"name={name}",
    )


def _by_text(el: Element) -> LocatorSuggestion | None:
    text = (el.text or "").strip()
    if not text or len(text) > 60:
        return None
    return LocatorSuggestion(
        strategy="text",
        confidence=70,
        reason="Visible text uniquely identifies the element but breaks if the copy changes.",
        playwright=f"page.get_by_text('{_css_escape(text)}')",
        selenium=f"driver.find_element(By.XPATH, \"//{el.tag}[normalize-space()='{text}']\")",
        css="",
        xpath=f"//{el.tag}[normalize-space()='{text}']",
        robotframework=f"xpath=//{el.tag}[normalize-space()='{text}']",
    )


def _by_css_class(el: Element) -> LocatorSuggestion | None:
    classes = el.classes()
    if not classes:
        return None
    css = el.tag + "".join(f".{c}" for c in classes[:3])
    return LocatorSuggestion(
        strategy="css",
        confidence=55,
        reason="CSS class combination is available but styling classes change frequently.",
        playwright=f'page.locator("{css}")',
        selenium=f'driver.find_element(By.CSS_SELECTOR, "{css}")',
        css=css,
        xpath="",
        robotframework=f"css={css}",
    )


# Generators in descending stability order.
_GENERATORS = (_by_test_id, _by_id, _by_role, _by_name, _by_text, _by_css_class)


def generate_suggestions(el: Element) -> list[LocatorSuggestion]:
    """Produce every applicable locator strategy for an element."""
    out: list[LocatorSuggestion] = []
    for gen in _GENERATORS:
        suggestion = gen(el)
        if suggestion is not None:
            out.append(suggestion)
    return out
